### ISSUE TITLE
Crash during SAM3 Propagate

### ISSUE THREAD

**Issue by jason-mightynice** [PozzettiAndrea/ComfyUI-SAM3#63]
UPDATE: for python 3.13, I updated pytorch to the nightly build and it works. 

pytorch version: 2.11.0.dev20251220+cu128
xformers version: 0.0.34+0b76a47.d20251221 

UPDATE2: went back to pytorch 2.9.1 and it worked. When torch_generic_nms and cc_torch is installed, it crashed.

-----------------
Windows RTX5090
python3.13
pytorch version: 2.9.1+cu128
xformers version: 0.0.33.post2

SAM3 Text Segmentation works, but SAM3 Video Segmentation -> SAM3 Propagate crashes without any errors. Here is the log up to when comfyui exits.

TEST RESULTS: Works with python 3.12, 2.80/2.91 + cu128 

```
got prompt
WARNING: 'NoneType' object has no attribute 'session_uuid'
[IS_CHANGED DEBUG] SAM3Propagate: video_state id=140727814648304, session=None
[IS_CHANGED DEBUG] SAM3Propagate: returning (140727814648304, 0, 3, 'forward')
WARNING: 'NoneType' object has no attribute 'shape'
[SAM3 Video] CACHE MISS - computing new video_state for key=ec8221bc
[VRAM] Before video segmentation: 0.01GB allocated, 0.03GB reserved
[SAM3 Video] Saving 30 frames to C:\Users\FREELA~1\AppData\Local\Temp\sam3_e6991541_9j8j_byp
[SAM3 Video] Frames saved successfully
[SAM3 Video] Initialized session e6991541
[SAM3 Video] Frames: 30, Size: 720x1280
[SAM3 Video] Prompt mode: text
[SAM3 Video] Added text prompt: obj=1, text='person'
[SAM3 Video] Total prompts: 1
[VRAM] After video segmentation: 0.01GB allocated, 0.03GB reserved
[SAM3] Load device: cuda:0, Offload device: cpu
[SAM3] Loading unified model from: D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\models\sam3\sam3.pt
[SAM3] Using BPE tokenizer: D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM3\nodes\sam3_lib\bpe_simple_vocab_16e6.txt.gz
[SAM3] Building SAM3 unified model...
Sam3VideoPredictor using device: cuda
INFO 2025-12-20 16:01:18,574 37252 sam3_video_base.py: 124: setting max_num_objects=10000 and num_obj_for_compile=16
[SAM3] Loading PyTorch checkpoint: D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\models\sam3\sam3.pt
[SAM3] Added 309 keys for detector.inst_interactive_predictor
[SAM3] Video predictor loaded successfully
[SAM3] Creating SAM3 processor...
[SAM3] Processor created successfully
[SAM3] Unified model ready (size: 3289.9 MB)
[SAM3 Propagate] CACHE MISS - running propagation for session=e6991541
[SAM3 Video] Starting propagation: frames 0 to 3
[SAM3 Video] Prompts: 1
[VRAM] Before propagation start: 3.46GB allocated, 3.47GB reserved
[VRAM] Before reconstruction (in autocast): 3.46GB allocated, 3.47GB reserved
[SAM3 Video] Reconstructing inference state for e6991541
[VRAM] Before start_session: 3.46GB allocated, 3.47GB reserved
[VRAM] Before init_state: 3.46GB allocated, 3.47GB reserved
frame loading (image folder) [rank=0]: 100%|███████████████████████████████████████████| 30/30 [00:00<00:00, 34.34it/s]
[VRAM] After init_state: 3.63GB allocated, 3.66GB reserved
[SAM3 Video] Active sessions in _ALL_INFERENCE_STATES: 1
[VRAM] After start_session: 3.63GB allocated, 3.66GB reserved
[SAM3 Video] Applying text prompt: frame=0, obj=1

D:\ComfyUI_windows_latest\ComfyUI_windows_portable>pause
Press any key to continue . . .
```
